name: CI Pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pygame xvfb

      - name: Install Python dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov flake8 black pygame

      - name: Check formatting with Black
        run: |
          black --check --diff .

      - name: Run Flake8 
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=30 --max-line-length=100 --statistics
          

      - name: Run Pytest with coverage using xvfb
        run: |
          xvfb-run -a pytest --cov=./ --cov-report=xml
